"use strict";

const test = require("/test/test-helper.xqy");
const {createImplicitSchema, storeImplicitSchema} = require("/mlGraphqlLibOpticApi");
const admin = require("/MarkLogic/admin.xqy");
const assertions = [];

// Given implicit schema generated by the user
// When the user stores it in the database
// Then test if schema is saved successfully in Schemas database with desired data.
const createdSchema = createImplicitSchema();
const createdSchemaString = JSON.stringify(createdSchema);

storeImplicitSchema();

const config = admin.getConfiguration();
const schemaDatabaseId = admin.databaseGetSchemaDatabase(config, xdmp.database());

const javascriptString = "fn.document('/graphql/implicitSchema.sdl');";

let documentSaved = xdmp.eval(javascriptString,  null,
  {
    "database": schemaDatabaseId
  });
documentSaved = JSON.stringify(documentSaved);

xdmp.log(`Actual Result of documentSaved=>\n${documentSaved}`, "info");

assertions.push(
  test.assertEqual(createdSchemaString, documentSaved, "The GraphQL implicit schema saved should match the generated one")
);

assertions;